### ISSUE TITLE
`x86_irq_mask()` fails to mask the master PIC properly

### ISSUE THREAD

**Issue by Arignir** [mohamed-anwar/Aquila#25]
Hello @mohamed-anwar , it's been a long time :)

I hope everything is fine on your side!

I was looking at the implementation of the 8259 Programmable Interrupt  Controller ([kernel/arch/i386/platform/misc/pic.c](https://github.com/mohamed-anwar/Aquila/blob/master/kernel/arch/i386/platform/misc/pic.c)) and found what is probably small typo or copy/past error that alters the behaviour of the `x86_irq_mask()` function.

```c
/* The mask value currently on slave:master */
static uint16_t pic_mask = 0xFFFF;

void x86_irq_mask(int irq)
{
    if (irq < 8) {  /* Master */
        pic_mask |= 1 << irq;
        io_out8(&master,  PIC_DATA, (pic_mask >> 8) & 0xFF);
    } else if (irq < 16) {  /* Slave */
        pic_mask |= 1 << irq;
        io_out8(&slave,  PIC_DATA, (pic_mask >> 8) & 0xFF);
    } else {
        panic("Invalid IRQ number\n");
    }
}
```

The mask given to the master PIC looks like it's the one of the slave.

Good luck in your study and on your work on Aquila,

Arignir

**Comment by mohamed-anwar** [comment]
Hello @Arignir nice to hear from you! I hope everything is going well.
It was most likely a copy/paste problem, thank you for pointing it out.
