### ISSUE TITLE
Is it x86_64 or itanium

### ISSUE THREAD

**Issue by TheStr3ak5** [mohamed-anwar/Aquila#26]
In the README you name IA64 as one of the goals, is it a misspelling for amd64/x86_64 or is it genuinely IA64, aka itanium ?
If its the latter, why?

**Comment by mohamed-anwar** [comment]
Hello @TheStr3ak5 it's x86_64 (or IA32e in Intel Manuals), it's a silly mistake that I forgot to change in the README. I'm not planing to support Itanium at all. It's fixed now.
