### ISSUE TITLE
IBM XT 8086

### ISSUE THREAD

**Issue by toncho11** [mohamed-anwar/Aquila#29]
Hi,

You never say if it is 32 bit operating system. That needs to be clarified. 
I would like to see a 16 bit version. This way I can try it on my vintage 16 bit computer with 640 kb RAM. 

You can try these 16 bit compilers:
- https://github.com/tkchia/gcc-ia16
- http://openwatcom.org/

16 bit os that allows for programs to be easily written or ported will be fun.

**Comment by mohamed-anwar** [comment]
Hello @toncho11 

Currently Aquila relies heavily on paging, I do have plans to add support for platforms without paging, but it's not scheduled any time in the near future, sorry for any inconvenience. If you are interested enough though, you could try and add support for 16-bit 8086.

**Comment by toncho11** [comment]
I see. 
One idea is to make your own paging ... which will be slow. There can be per process swapping. Most vintage computers now use flash or micro sd cards, so swapping is actually limited but the IO bands and the CPU.  It means that swapping is probably not that bad as it used to be.
