### ISSUE TITLE
building newlib crt0 missing issue

### ISSUE THREAD

**Issue by nagyation** [mohamed-anwar/Aquila#3]
`cp: cannot stat 'sys/crt0.o': No such file or directory`
`make[4]: *** [Makefile:1046: crt0.o] Error 1`

**Comment by nagyation** [comment]
At last I got it to build and work successfully, the problem was in building automake, it was built because the Perl version is newer - maybe because I used arch linux -, I used a patch found in the [AUR](https://aur.archlinux.org/packages/automake-1.11/ ) of arch linux
after applying it things worked well.

**Comment by mohamed-anwar** [comment]
Nice work! Do you think that should be considered an issue? we can build Perl as part of the build-system, but that would be over-complication. We can also use Docker, for example, with all binaries pre-built with correct versions.

**Comment by nagyation** [comment]
I think we could just use the patch before building automake, if we could also know the exact perl version that works, we can check over the version to know whether or not to apply the patch
I'll work on the script a little more - maybe tomorrow-, I've added a user option for the script to use the jobs option "-jN" of make to parallel the building, that save alot of time for good processors

**Comment by mohamed-anwar** [comment]
Since you have Arch Linux (I use Fedora btw) experiment with a few possibilities and try to make the build-system as generic as possible, I believe we can switch to Makefile instead of bash script. I almost never use the build-system in the repository locally, it's intended only for Travis (my local build system uses -j4, caches and other things but are very specific to my system).

**Comment by nagyation** [comment]
I think the script is good now, It's stable and works as intended for now, maybe if it gets a little more complex in the future we look for alternatives

**Comment by mohamed-anwar** [comment]
Time to close the issue then :)
