### ISSUE TITLE
How Can I get the build-tools?

### ISSUE THREAD

**Issue by xiaokang00010** [mohamed-anwar/Aquila#30]
I can't find the build-tools in this project

**Comment by dimutch833** [comment]
### same problem

**Comment by xiaokang00010** [comment]
I can download build-tools in v0.0.1a-dev-build004.Is it working in newest version?

**Comment by dimutch833** [comment]
why u need old version

**Comment by dimutch833** [comment]
idk but i dont see build tools in newest version

**Comment by xiaokang00010** [comment]
Ahh...

**Comment by 0kalekale** [comment]
checkout to d2d655cb2b07963cd73f7a59ddb11371628b84a2, i have no idea why the maintainers nuked `build-tools/`

**Comment by ret7020** [comment]
build-tools folder in .gitignore and I can't understand why

**Comment by Dashbloxx** [comment]
**Solution:**
Clone Aquila, and run:
```
git reset --hard 307f127462a9c1066258811ffc40adb3ee8007e8
```
Then you copy the `build-tools` folder to the latest release!

**Comment by xiaokang00010** [comment]
> **Solution:** Clone Aquila, and run:
> 
> ```
> git reset --hard 307f127462a9c1066258811ffc40adb3ee8007e8
> ```
> 
> Then you copy the `build-tools` folder to the latest release!

Thanks for your reply. I am so surprised that I can receive a reply from my issue over 2 years ago. And I noticed that this project has no longer be maintained since 2019. What a pity.
