### ISSUE TITLE
use `make -j $(nproc)` instead of `make` in `build.sh`

### ISSUE THREAD

**Issue by lordadamson** [mohamed-anwar/Aquila#4]
building binutils and gcc takes so much time man :smile: and life is short.
using `-j $(nproc)` should make it much faster.

I'm trying that on my machine right now and will pull request if it builds with no issues.

**Comment by nagyation** [comment]
Did the automake build fine from the script? if so could you provide your perl version?

**Comment by lordadamson** [comment]
it sure did.
```
$ perl --version

This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 68 registered patches, see perl -V for more detail)
```

**Comment by lordadamson** [comment]
and it passed travis CI too

**Comment by nagyation** [comment]
@mohamed-anwar Then it needs the patch from version 26 :D I looked in its [Changelog](https://perldoc.perl.org/perl5260delta.html)  they have changed the use of literal "{" character, I will add that after you look at [submitted](https://github.com/mohamed-anwar/Aquila/pull/8) pull request,
sometimes I hate Arch linux for being so up to date :'D
