### ISSUE TITLE
add documentation on how to build the source code

### ISSUE THREAD

**Issue by lordadamson** [mohamed-anwar/Aquila#5]
right now I'm following the `.travis.yml` to build it.

It all works well I may add some instructions to the `README.md`

**Comment by mohamed-anwar** [comment]
I think it would be better to update the Wiki

**Comment by lordadamson** [comment]
sounds good :smile:

**Comment by lordadamson** [comment]
hi, I just found out that I can't pull request the wiki. haalp, what do? lol

**Comment by lordadamson** [comment]
oh thank you :heart: I'll put the instructions once I'd recovered from my mum's ma7shy :smile:

**Comment by mohamed-anwar** [comment]
Good luck with that :"D
