### ISSUE TITLE
when using make -j 4 aquila.iso the build fails

### ISSUE THREAD

**Issue by lordadamson** [mohamed-anwar/Aquila#9]
It builds okay without concurrent jobs.
I believe some of the rules depend on other rules but that's not explicitly stated in the Makefile

**Comment by mohamed-anwar** [comment]
Yes, you can't use concurrent jobs in Aquila itself, not yet. The system still has many bugs, will try to work on it ASAP though.

**Comment by lordadamson** [comment]
I don't think it's a serious bug :smile: You probably just need to state the dependencies of each rule so that make would not run two interdependent rules at the same time.

Example:
```
rule1:
     do stuff that depend on rule2

rule2:
    do stuff

all: rule1 rule2
```

This will fail because make will run rule1 and 2 concurrently even though rule1 depends on 2.
To fix all we need to do is:
```
rule1: rule2
     do stuff that depend on rule2

rule2:
    do stuff

all: rule1
```

**Comment by mohamed-anwar** [comment]
Not just that, the Makefiles won't see changes in headers for example (they are not listed as dependencies). The Perl script in `kernel/scripts` does nothing more than an exact copy of Makefile (it used to be an actual script), it's been a long while since I looked at the Makefiles actually.

**Comment by mohamed-anwar** [comment]
Fixed `-j $(nproc)` in kernel for now, but the solution is not pretty.

**Comment by lordadamson** [comment]
good job :+1:
